/**
 * Switch Database REST API
 * Switch API is the primary endpoint of data sevices and Switch DB's platform. You can do adding, editing, deleting or listing data works to your database with query operations by using this low-level API based on HTTP.
 *
 * OpenAPI spec version: 1.2.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.SwitchDatabaseRestApi);
  }
}(this, function(expect, SwitchDatabaseRestApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new SwitchDatabaseRestApi.AddResponse();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('AddResponse', function() {
    it('should create an instance of AddResponse', function() {
      // uncomment below and update the code to test AddResponse
      //var instane = new SwitchDatabaseRestApi.AddResponse();
      //expect(instance).to.be.a(SwitchDatabaseRestApi.AddResponse);
    });

    it('should have the property responseTime (base name: "ResponseTime")', function() {
      // uncomment below and update the code to test the property responseTime
      //var instane = new SwitchDatabaseRestApi.AddResponse();
      //expect(instance).to.be();
    });

    it('should have the property response (base name: "Response")', function() {
      // uncomment below and update the code to test the property response
      //var instane = new SwitchDatabaseRestApi.AddResponse();
      //expect(instance).to.be();
    });

    it('should have the property listItemId (base name: "ListItemId")', function() {
      // uncomment below and update the code to test the property listItemId
      //var instane = new SwitchDatabaseRestApi.AddResponse();
      //expect(instance).to.be();
    });

  });

}));
